main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.11"
author: mictali
description: A Treasure Hunting plugin
commands:
  info:
    description: Dumps info on all existing barrels to log
    usage: "/deadmanschestplugin info"
  flush:
    description: Removes all existing barrels
    usage: "/deadmanschestplugin flush"
  chest:
    description: Spawn a deadman's chest
    usage: "/deadmanschestplugin chest"
